//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDatasetLoader.AnalysisService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AnalysisService.ITonalService")]
    public interface ITonalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITonalService/GetAnalysis", ReplyAction="http://tempuri.org/ITonalService/GetAnalysisResponse")]
        string GetAnalysis(string email, string text, string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITonalService/GetAnalysis", ReplyAction="http://tempuri.org/ITonalService/GetAnalysisResponse")]
        System.Threading.Tasks.Task<string> GetAnalysisAsync(string email, string text, string userName, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITonalServiceChannel : TestDatasetLoader.AnalysisService.ITonalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TonalServiceClient : System.ServiceModel.ClientBase<TestDatasetLoader.AnalysisService.ITonalService>, TestDatasetLoader.AnalysisService.ITonalService {
        
        public TonalServiceClient() {
        }
        
        public TonalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TonalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TonalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TonalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAnalysis(string email, string text, string userName, string password) {
            return base.Channel.GetAnalysis(email, text, userName, password);
        }
        
        public System.Threading.Tasks.Task<string> GetAnalysisAsync(string email, string text, string userName, string password) {
            return base.Channel.GetAnalysisAsync(email, text, userName, password);
        }
    }
}
